services:
  - type: web
    name: GabiCraft
    runtime: static
    rootDir: GabiCraft.Client
    buildCommand: npm install --no-audit --no-fund && npm run build
    staticPublishPath: ./out
    autoDeployTrigger: checksPass
